version: '2'
services:
  match:
    image: match:1.0
    ports:
        - 127.0.0.1:8888:8888
    command: ["/wait-for-it.sh", "-t", "60", "elasticsearch:9200", "--", "gunicorn", "-b", "0.0.0.0:8888", "-w", "4", "server:app"]
    links:
        - elasticsearch
    restart_policy:
        condition: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
        - discovery.type=single-node
    ports:
        - 127.0.0.1:9200:9200
    volumes:
        - esdata:/usr/share/elasticsearch/data
    restart_policy:
        condition: always

volumes:
  esdata:
    driver: local
